import {
  ACCOUNT_STATUSES,
  ACCOUNT_TYPES,
  ASSISTANT_ACTION_INTENTS,
  ASSISTANT_ACTION_STATUSES,
  ASSISTANT_CONFIRMATION_STATUSES,
  ASSISTANT_INTENTS,
  ASSISTANT_QUERY_STATUSES,
  BUDGET_STATUSES,
  CUSTOMER_STATUSES,
  DASHBOARD_HEALTH,
  EMPLOYEE_STATUSES,
  EMPLOYMENT_TYPES,
  FINANCE_CATEGORY_STATUSES,
  FINANCE_CATEGORY_TYPES,
  FINANCE_CURRENCIES,
  FINANCE_TRANSACTION_STATUSES,
  FINANCE_TRANSACTION_TYPES,
  LEAD_PRIORITIES,
  LEAD_SOURCES,
  LEAD_STATUSES,
  MEETING_STATUSES,
  MEETING_TYPES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_DELIVERY_STATUSES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_TYPES,
  OPPORTUNITY_STAGES,
  PAYMENT_METHODS,
  PROJECT_HEALTH,
  PROJECT_STATUSES,
  PROJECT_TYPES,
  REMINDER_FREQUENCIES,
  REMINDER_PRIORITIES,
  REMINDER_SOURCE_TYPES,
  REMINDER_STATUSES,
  REMINDER_TYPES,
  REMINDER_WEEKDAYS,
  ROLES,
  SALES_ACTIVITY_STATUSES,
  SALES_ACTIVITY_TYPES,
  TASK_PRIORITIES,
  TASK_STATUSES,
  USER_STATUSES,
  WHATSAPP_MESSAGE_STATUSES,
  WHATSAPP_MESSAGE_TYPES,
} from "../utils/constants";
import { dateTime, enumOf, money, ref, type JsonSchema } from "./helpers";

function props(properties: Record<string, JsonSchema>, required: string[] = []): JsonSchema {
  return { type: "object", additionalProperties: false, properties, ...(required.length ? { required } : {}) };
}

const objectId: JsonSchema = {
  type: "string",
  pattern: "^[a-fA-F0-9]{24}$",
  example: "64f0c2a1b8e4d12a9c7f0011",
  description: "MongoDB ObjectId",
};

export const componentSchemas: Record<string, JsonSchema> = {
  ObjectId: objectId,
  Role: enumOf(ROLES),
  UserStatus: enumOf(USER_STATUSES),
  EmploymentType: enumOf(EMPLOYMENT_TYPES),
  EmployeeStatus: enumOf(EMPLOYEE_STATUSES),
  TaskStatus: enumOf(TASK_STATUSES),
  TaskPriority: enumOf(TASK_PRIORITIES),
  ProjectType: enumOf(PROJECT_TYPES),
  ProjectStatus: enumOf(PROJECT_STATUSES),
  ProjectHealth: enumOf(PROJECT_HEALTH),
  MeetingType: enumOf(MEETING_TYPES),
  MeetingStatus: enumOf(MEETING_STATUSES),
  LeadSource: enumOf(LEAD_SOURCES),
  LeadStatus: enumOf(LEAD_STATUSES),
  LeadPriority: enumOf(LEAD_PRIORITIES),
  CustomerStatus: enumOf(CUSTOMER_STATUSES),
  OpportunityStage: enumOf(OPPORTUNITY_STAGES),
  SalesActivityType: enumOf(SALES_ACTIVITY_TYPES),
  SalesActivityStatus: enumOf(SALES_ACTIVITY_STATUSES),
  AccountType: enumOf(ACCOUNT_TYPES),
  AccountStatus: enumOf(ACCOUNT_STATUSES),
  FinanceCategoryType: enumOf(FINANCE_CATEGORY_TYPES),
  FinanceCategoryStatus: enumOf(FINANCE_CATEGORY_STATUSES),
  FinanceTransactionType: enumOf(FINANCE_TRANSACTION_TYPES),
  FinanceTransactionStatus: enumOf(FINANCE_TRANSACTION_STATUSES),
  PaymentMethod: enumOf(PAYMENT_METHODS),
  FinanceCurrency: enumOf(FINANCE_CURRENCIES),
  BudgetStatus: enumOf(BUDGET_STATUSES),
  DashboardHealth: enumOf(DASHBOARD_HEALTH),
  AssistantIntent: enumOf(ASSISTANT_INTENTS),
  AssistantQueryStatus: enumOf(ASSISTANT_QUERY_STATUSES),
  AssistantActionIntent: enumOf(ASSISTANT_ACTION_INTENTS),
  AssistantActionStatus: enumOf(ASSISTANT_ACTION_STATUSES),
  AssistantConfirmationStatus: enumOf(ASSISTANT_CONFIRMATION_STATUSES),
  ReminderType: enumOf(REMINDER_TYPES),
  ReminderSourceType: enumOf(REMINDER_SOURCE_TYPES),
  ReminderPriority: enumOf(REMINDER_PRIORITIES),
  ReminderStatus: enumOf(REMINDER_STATUSES),
  ReminderFrequency: enumOf(REMINDER_FREQUENCIES),
  ReminderWeekday: enumOf(REMINDER_WEEKDAYS),
  NotificationType: enumOf(NOTIFICATION_TYPES),
  NotificationCategory: enumOf(NOTIFICATION_CATEGORIES),
  NotificationPriority: enumOf(NOTIFICATION_PRIORITIES),
  NotificationDeliveryStatus: enumOf(NOTIFICATION_DELIVERY_STATUSES),
  NotificationChannelName: enumOf(NOTIFICATION_CHANNELS),
  WhatsAppMessageType: enumOf(WHATSAPP_MESSAGE_TYPES),
  WhatsAppMessageStatus: enumOf(WHATSAPP_MESSAGE_STATUSES),

  PaginationMeta: props(
    {
      page: { type: "integer", example: 1 },
      limit: { type: "integer", example: 20 },
      total: { type: "integer", example: 120 },
      totalPages: { type: "integer", example: 6 },
      hasNextPage: { type: "boolean", example: true },
      hasPreviousPage: { type: "boolean", example: false },
    },
    ["page", "limit", "total", "totalPages", "hasNextPage", "hasPreviousPage"],
  ),

  ApiSuccess: props(
    {
      success: { type: "boolean", example: true },
      message: { type: "string", example: "Success" },
      data: { description: "Endpoint-specific payload", nullable: true },
      meta: ref("PaginationMeta"),
    },
    ["success", "message"],
  ),

  FieldError: props({
    field: { type: "string", example: "message" },
    message: { type: "string", example: "message is required" },
  }),

  ApiError: props(
    {
      success: { type: "boolean", example: false },
      message: { type: "string", example: "Validation failed" },
      errors: { type: "array", items: ref("FieldError") },
    },
    ["success", "message", "errors"],
  ),

  User: props({
    id: objectId,
    name: { type: "string", example: "Priya Sharma" },
    email: { type: "string", format: "email", example: "priya@example.com" },
    phone: { type: "string", example: "9876500801" },
    role: ref("Role"),
    status: ref("UserStatus"),
    isActive: { type: "boolean" },
    lastLoginAt: { ...dateTime(), nullable: true },
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),

  AuthTokens: props({
    user: ref("User"),
    accessToken: { type: "string", description: "JWT access token (15 minutes by default)" },
    refreshToken: { type: "string", description: "Refresh token (7 days, hashed at rest)" },
  }),

  RegisterRequest: props(
    {
      name: { type: "string", minLength: 2, maxLength: 120 },
      email: { type: "string", format: "email" },
      phone: { type: "string", example: "9876500801", description: "10-digit Indian mobile number" },
      password: { type: "string", minLength: 8, format: "password" },
      role: { ...enumOf(["EMPLOYEE"]), description: "Public register always creates EMPLOYEE" },
    },
    ["name", "email", "phone", "password"],
  ),

  LoginRequest: props(
    {
      email: { type: "string", format: "email", example: "admin@example.com" },
      password: { type: "string", format: "password", example: "SecurePassword123" },
    },
    ["email", "password"],
  ),

  RefreshRequest: props({ refreshToken: { type: "string", minLength: 10 } }, ["refreshToken"]),
  LogoutRequest: props({ refreshToken: { type: "string", minLength: 10 } }),

  CreateUserRequest: props(
    {
      name: { type: "string" },
      email: { type: "string", format: "email" },
      phone: { type: "string" },
      password: { type: "string", format: "password" },
      role: ref("Role"),
      status: ref("UserStatus"),
    },
    ["name", "email", "password"],
  ),
  UpdateUserRequest: props({
    name: { type: "string" },
    phone: { type: "string" },
    role: ref("Role"),
    status: ref("UserStatus"),
    isActive: { type: "boolean" },
  }),
  UpdateUserStatusRequest: props({ status: ref("UserStatus") }, ["status"]),

  Employee: props({
    id: objectId,
    employeeId: { type: "string" },
    userId: objectId,
    employeeCode: { type: "string", example: "EMP-000001" },
    firstName: { type: "string" },
    lastName: { type: "string" },
    displayName: { type: "string" },
    email: { type: "string", format: "email" },
    phone: { type: "string" },
    department: { type: "string" },
    designation: { type: "string" },
    managerId: { ...objectId, nullable: true },
    joiningDate: dateTime(),
    employmentType: ref("EmploymentType"),
    location: { type: "string" },
    status: ref("EmployeeStatus"),
    profileImage: { type: "string" },
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateEmployeeRequest: props(
    {
      userId: objectId,
      firstName: { type: "string" },
      lastName: { type: "string" },
      displayName: { type: "string" },
      phone: { type: "string" },
      department: { type: "string" },
      designation: { type: "string" },
      managerId: objectId,
      joiningDate: dateTime(),
      employmentType: ref("EmploymentType"),
      location: { type: "string" },
      status: ref("EmployeeStatus"),
      profileImage: { type: "string" },
    },
    ["userId", "firstName", "lastName"],
  ),
  UpdateEmployeeRequest: props({
    firstName: { type: "string" },
    lastName: { type: "string" },
    displayName: { type: "string" },
    phone: { type: "string" },
    department: { type: "string" },
    designation: { type: "string" },
    managerId: { nullable: true, allOf: [objectId] },
    joiningDate: dateTime(),
    employmentType: ref("EmploymentType"),
    location: { type: "string" },
    status: ref("EmployeeStatus"),
    profileImage: { type: "string" },
  }),
  UpdateEmployeeStatusRequest: props({ status: ref("EmployeeStatus") }, ["status"]),

  Task: props({
    id: objectId,
    taskId: { type: "string", example: "TASK-000001" },
    title: { type: "string", example: "Call ABC Industries" },
    description: { type: "string" },
    assignedTo: objectId,
    createdBy: objectId,
    projectId: { ...objectId, nullable: true },
    priority: ref("TaskPriority"),
    status: ref("TaskStatus"),
    dueDate: { ...dateTime(), nullable: true },
    reminderAt: { ...dateTime(), nullable: true },
    startedAt: { ...dateTime(), nullable: true },
    completedAt: { ...dateTime(), nullable: true },
    cancelledAt: { ...dateTime(), nullable: true },
    completionNote: { type: "string" },
    cancellationReason: { type: "string" },
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateTaskRequest: props(
    {
      title: { type: "string", example: "Call ABC Industries" },
      description: { type: "string" },
      assignedTo: objectId,
      projectId: objectId,
      priority: ref("TaskPriority"),
      dueDate: dateTime(),
      reminderAt: dateTime(),
    },
    ["title", "assignedTo"],
  ),
  UpdateTaskRequest: props({
    title: { type: "string" },
    description: { type: "string" },
    assignedTo: objectId,
    projectId: { nullable: true, allOf: [objectId] },
    priority: ref("TaskPriority"),
    dueDate: dateTime(),
    reminderAt: dateTime(),
  }),
  UpdateTaskStatusRequest: props({
    status: ref("TaskStatus"),
    completionNote: { type: "string", description: "Only when status is COMPLETED" },
    reason: { type: "string", description: "Only when status is CANCELLED" },
  }, ["status"]),
  UpdateTaskAssigneeRequest: props({ assignedTo: objectId }, ["assignedTo"]),
  TaskCounts: props({
    pending: { type: "integer" },
    inProgress: { type: "integer" },
    completed: { type: "integer" },
    cancelled: { type: "integer" },
    overdue: { type: "integer" },
  }),

  Project: props({
    id: objectId,
    projectId: { type: "string", example: "PROJ-000001" },
    name: { type: "string", example: "Chennai Warehouse" },
    code: { type: "string" },
    description: { type: "string" },
    location: { type: "string" },
    projectType: ref("ProjectType"),
    managerId: objectId,
    members: { type: "array", items: objectId },
    status: ref("ProjectStatus"),
    progress: { type: "integer", minimum: 0, maximum: 100 },
    budget: money("Project budget in whole INR"),
    actualExpense: money(),
    startDate: { ...dateTime(), nullable: true },
    expectedEndDate: { ...dateTime(), nullable: true },
    completedAt: { ...dateTime(), nullable: true },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateProjectRequest: props(
    {
      name: { type: "string" },
      code: { type: "string" },
      description: { type: "string" },
      location: { type: "string" },
      projectType: ref("ProjectType"),
      managerId: objectId,
      members: { type: "array", items: objectId, maxItems: 50 },
      status: ref("ProjectStatus"),
      progress: { type: "integer", minimum: 0, maximum: 100 },
      budget: money(),
      startDate: dateTime(),
      expectedEndDate: dateTime(),
    },
    ["name", "projectType", "managerId"],
  ),
  UpdateProjectRequest: props({
    name: { type: "string" },
    code: { type: "string" },
    description: { type: "string" },
    location: { type: "string" },
    projectType: ref("ProjectType"),
    managerId: objectId,
    members: { type: "array", items: objectId },
    status: ref("ProjectStatus"),
    progress: { type: "integer" },
    budget: money(),
    startDate: dateTime(),
    expectedEndDate: dateTime(),
  }),
  UpdateProjectStatusRequest: props({ status: ref("ProjectStatus") }, ["status"]),
  UpdateProjectManagerRequest: props({ managerId: objectId }, ["managerId"]),
  UpdateProjectMembersRequest: props({ members: { type: "array", items: objectId, maxItems: 50 } }, ["members"]),

  Meeting: props({
    id: objectId,
    meetingId: { type: "string", example: "MTG-000001" },
    title: { type: "string" },
    description: { type: "string" },
    meetingType: ref("MeetingType"),
    organizerId: objectId,
    participants: { type: "array", items: objectId, description: "Employee ObjectIds" },
    projectId: { ...objectId, nullable: true },
    location: { type: "string" },
    startTime: dateTime(),
    endTime: dateTime(),
    timezone: { type: "string", example: "Asia/Kolkata", description: "IANA timezone used for local interpretation" },
    status: ref("MeetingStatus"),
    notes: { type: "string" },
    cancellationReason: { type: "string" },
    cancelledAt: { ...dateTime(), nullable: true },
    completedAt: { ...dateTime(), nullable: true },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateMeetingRequest: props(
    {
      title: { type: "string" },
      description: { type: "string" },
      meetingType: ref("MeetingType"),
      participants: { type: "array", items: objectId, maxItems: 50 },
      projectId: objectId,
      location: { type: "string" },
      startTime: dateTime(),
      endTime: dateTime(),
      timezone: { type: "string", example: "Asia/Kolkata" },
    },
    ["title", "startTime", "endTime"],
  ),
  UpdateMeetingRequest: props({
    title: { type: "string" },
    description: { type: "string" },
    meetingType: ref("MeetingType"),
    participants: { type: "array", items: objectId },
    projectId: { nullable: true, allOf: [objectId] },
    location: { type: "string" },
    startTime: dateTime(),
    endTime: dateTime(),
    timezone: { type: "string" },
    notes: { type: "string" },
  }),
  RescheduleMeetingRequest: props(
    { startTime: dateTime(), endTime: dateTime(), timezone: { type: "string" } },
    ["startTime", "endTime"],
  ),
  UpdateMeetingStatusRequest: props({ status: ref("MeetingStatus"), notes: { type: "string" } }, ["status"]),
  CancelMeetingRequest: props({ reason: { type: "string", minLength: 1, maxLength: 500 } }, ["reason"]),

  Lead: props({
    id: objectId,
    leadId: { type: "string", example: "LEAD-000001" },
    name: { type: "string" },
    companyName: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    alternatePhone: { type: "string" },
    source: ref("LeadSource"),
    industry: { type: "string" },
    location: { type: "string" },
    description: { type: "string" },
    assignedTo: { ...objectId, nullable: true },
    status: ref("LeadStatus"),
    priority: ref("LeadPriority"),
    estimatedValue: money(),
    expectedCloseDate: { ...dateTime(), nullable: true },
    nextFollowUpAt: { ...dateTime(), nullable: true },
    convertedAt: { ...dateTime(), nullable: true },
    convertedCustomerId: { ...objectId, nullable: true },
    convertedOpportunityId: { ...objectId, nullable: true },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateLeadRequest: props(
    {
      name: { type: "string" },
      companyName: { type: "string" },
      email: { type: "string" },
      phone: { type: "string" },
      alternatePhone: { type: "string" },
      source: ref("LeadSource"),
      industry: { type: "string" },
      location: { type: "string" },
      description: { type: "string" },
      assignedTo: objectId,
      priority: ref("LeadPriority"),
      estimatedValue: money(),
      expectedCloseDate: dateTime(),
      nextFollowUpAt: dateTime(),
    },
    ["name", "source"],
  ),
  UpdateLeadRequest: props({
    name: { type: "string" },
    companyName: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    alternatePhone: { type: "string" },
    source: ref("LeadSource"),
    industry: { type: "string" },
    location: { type: "string" },
    description: { type: "string" },
    assignedTo: objectId,
    priority: ref("LeadPriority"),
    estimatedValue: money(),
    expectedCloseDate: dateTime(),
    nextFollowUpAt: dateTime(),
  }),
  UpdateLeadStatusRequest: props({ status: ref("LeadStatus") }, ["status"]),
  UpdateLeadFollowUpRequest: props({ nextFollowUpAt: dateTime() }, ["nextFollowUpAt"]),
  ConvertLeadRequest: props({
    createCustomer: { type: "boolean", default: true },
    createOpportunity: { type: "boolean", default: true },
    opportunity: props({
      title: { type: "string" },
      estimatedValue: money(),
      expectedCloseDate: dateTime(),
      description: { type: "string" },
      stage: ref("OpportunityStage"),
      probability: { type: "integer", minimum: 0, maximum: 100 },
    }),
  }),

  Customer: props({
    id: objectId,
    customerId: { type: "string", example: "CUST-000001" },
    name: { type: "string" },
    companyName: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    alternatePhone: { type: "string" },
    industry: { type: "string" },
    location: { type: "string" },
    address: { type: "string" },
    taxIdentifier: { type: "string" },
    assignedTo: { ...objectId, nullable: true },
    sourceLeadId: { ...objectId, nullable: true },
    status: ref("CustomerStatus"),
    notes: { type: "string" },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateCustomerRequest: props(
    {
      name: { type: "string" },
      companyName: { type: "string" },
      email: { type: "string" },
      phone: { type: "string" },
      alternatePhone: { type: "string" },
      industry: { type: "string" },
      location: { type: "string" },
      address: { type: "string" },
      taxIdentifier: { type: "string" },
      assignedTo: objectId,
      status: ref("CustomerStatus"),
      notes: { type: "string" },
    },
    ["name"],
  ),
  UpdateCustomerRequest: props({
    name: { type: "string" },
    companyName: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    alternatePhone: { type: "string" },
    industry: { type: "string" },
    location: { type: "string" },
    address: { type: "string" },
    taxIdentifier: { type: "string" },
    assignedTo: objectId,
    notes: { type: "string" },
  }),
  UpdateCustomerStatusRequest: props({ status: ref("CustomerStatus") }, ["status"]),

  Opportunity: props({
    id: objectId,
    opportunityId: { type: "string", example: "OPP-000001" },
    title: { type: "string" },
    customerId: objectId,
    leadId: { ...objectId, nullable: true },
    projectId: { ...objectId, nullable: true },
    assignedTo: { ...objectId, nullable: true },
    stage: ref("OpportunityStage"),
    probability: { type: "integer", minimum: 0, maximum: 100 },
    estimatedValue: money(),
    expectedCloseDate: { ...dateTime(), nullable: true },
    description: { type: "string" },
    nextFollowUpAt: { ...dateTime(), nullable: true },
    lostReason: { type: "string" },
    wonAt: { ...dateTime(), nullable: true },
    lostAt: { ...dateTime(), nullable: true },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateOpportunityRequest: props(
    {
      title: { type: "string" },
      customerId: objectId,
      leadId: objectId,
      projectId: objectId,
      assignedTo: objectId,
      stage: ref("OpportunityStage"),
      probability: { type: "integer", minimum: 0, maximum: 100 },
      estimatedValue: money(),
      expectedCloseDate: dateTime(),
      description: { type: "string" },
      nextFollowUpAt: dateTime(),
    },
    ["title", "customerId"],
  ),
  UpdateOpportunityRequest: props({
    title: { type: "string" },
    customerId: objectId,
    leadId: objectId,
    projectId: objectId,
    assignedTo: objectId,
    probability: { type: "integer" },
    estimatedValue: money(),
    expectedCloseDate: dateTime(),
    description: { type: "string" },
    nextFollowUpAt: dateTime(),
  }),
  UpdateOpportunityStageRequest: props({
    stage: ref("OpportunityStage"),
    lostReason: { type: "string", description: "Required when stage is LOST" },
  }, ["stage"]),

  SalesActivity: props({
    id: objectId,
    activityId: { type: "string", example: "ACT-000001" },
    type: ref("SalesActivityType"),
    title: { type: "string" },
    description: { type: "string" },
    leadId: { ...objectId, nullable: true },
    customerId: { ...objectId, nullable: true },
    opportunityId: { ...objectId, nullable: true },
    employeeId: { ...objectId, nullable: true },
    scheduledAt: { ...dateTime(), nullable: true },
    completedAt: { ...dateTime(), nullable: true },
    status: ref("SalesActivityStatus"),
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateSalesActivityRequest: props(
    {
      type: ref("SalesActivityType"),
      title: { type: "string" },
      description: { type: "string" },
      leadId: objectId,
      customerId: objectId,
      opportunityId: objectId,
      employeeId: objectId,
      scheduledAt: dateTime(),
      status: ref("SalesActivityStatus"),
    },
    ["type", "title"],
  ),
  UpdateSalesActivityRequest: props({
    type: ref("SalesActivityType"),
    title: { type: "string" },
    description: { type: "string" },
    leadId: objectId,
    customerId: objectId,
    opportunityId: objectId,
    employeeId: objectId,
    scheduledAt: dateTime(),
  }),
  UpdateSalesActivityStatusRequest: props({ status: ref("SalesActivityStatus") }, ["status"]),

  Account: props({
    id: objectId,
    accountId: { type: "string", example: "ACC-000001" },
    name: { type: "string" },
    code: { type: "string" },
    type: ref("AccountType"),
    description: { type: "string" },
    openingBalance: money(),
    currentBalance: money(),
    currency: ref("FinanceCurrency"),
    status: ref("AccountStatus"),
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateAccountRequest: props(
    {
      name: { type: "string" },
      code: { type: "string", example: "CASH-01" },
      type: ref("AccountType"),
      description: { type: "string" },
      openingBalance: money(),
      currency: ref("FinanceCurrency"),
    },
    ["name", "code", "type"],
  ),
  UpdateAccountRequest: props({
    name: { type: "string" },
    description: { type: "string" },
    status: ref("AccountStatus"),
  }),

  FinanceCategory: props({
    id: objectId,
    categoryId: { type: "string", example: "CAT-000001" },
    name: { type: "string" },
    code: { type: "string" },
    type: ref("FinanceCategoryType"),
    description: { type: "string" },
    status: ref("FinanceCategoryStatus"),
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateFinanceCategoryRequest: props(
    {
      name: { type: "string" },
      code: { type: "string" },
      type: ref("FinanceCategoryType"),
      description: { type: "string" },
      status: ref("FinanceCategoryStatus"),
    },
    ["name", "code", "type"],
  ),
  UpdateFinanceCategoryRequest: props({
    name: { type: "string" },
    description: { type: "string" },
    status: ref("FinanceCategoryStatus"),
    type: ref("FinanceCategoryType"),
  }),

  FinanceTransaction: props({
    id: objectId,
    transactionId: { type: "string", example: "TXN-000001" },
    type: ref("FinanceTransactionType"),
    accountId: objectId,
    counterpartyAccountId: { ...objectId, nullable: true },
    categoryId: { ...objectId, nullable: true },
    amount: money("Whole INR rupees"),
    currency: ref("FinanceCurrency"),
    description: { type: "string" },
    referenceType: { type: "string" },
    referenceId: { type: "string" },
    projectId: { ...objectId, nullable: true },
    customerId: { ...objectId, nullable: true },
    opportunityId: { ...objectId, nullable: true },
    transactionDate: dateTime(),
    status: ref("FinanceTransactionStatus"),
    paymentMethod: ref("PaymentMethod"),
    externalReference: { type: "string" },
    notes: { type: "string" },
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateIncomeRequest: props(
    {
      accountId: objectId,
      categoryId: objectId,
      amount: money(),
      currency: ref("FinanceCurrency"),
      description: { type: "string" },
      projectId: objectId,
      customerId: objectId,
      opportunityId: objectId,
      transactionDate: dateTime(),
      paymentMethod: ref("PaymentMethod"),
      externalReference: { type: "string" },
      notes: { type: "string" },
      status: ref("FinanceTransactionStatus"),
    },
    ["accountId", "categoryId", "amount"],
  ),
  CreateExpenseRequest: props(
    {
      accountId: objectId,
      categoryId: objectId,
      amount: money(),
      currency: ref("FinanceCurrency"),
      description: { type: "string" },
      projectId: objectId,
      customerId: objectId,
      opportunityId: objectId,
      transactionDate: dateTime(),
      paymentMethod: ref("PaymentMethod"),
      externalReference: { type: "string" },
      notes: { type: "string" },
      status: ref("FinanceTransactionStatus"),
    },
    ["accountId", "categoryId", "amount"],
  ),
  CreateTransferRequest: props(
    {
      fromAccountId: objectId,
      toAccountId: objectId,
      amount: money(),
      currency: ref("FinanceCurrency"),
      description: { type: "string" },
      transactionDate: dateTime(),
      notes: { type: "string" },
      status: ref("FinanceTransactionStatus"),
    },
    ["fromAccountId", "toAccountId", "amount"],
  ),
  UpdateTransactionStatusRequest: props({ status: ref("FinanceTransactionStatus") }, ["status"]),

  Budget: props({
    id: objectId,
    budgetId: { type: "string", example: "BUD-000001" },
    name: { type: "string" },
    projectId: { ...objectId, nullable: true },
    categoryId: { ...objectId, nullable: true },
    amount: money(),
    currency: ref("FinanceCurrency"),
    periodStart: dateTime(),
    periodEnd: dateTime(),
    status: ref("BudgetStatus"),
    createdBy: objectId,
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateBudgetRequest: props(
    {
      name: { type: "string" },
      projectId: objectId,
      categoryId: objectId,
      amount: money(),
      currency: ref("FinanceCurrency"),
      periodStart: dateTime(),
      periodEnd: dateTime(),
      status: ref("BudgetStatus"),
    },
    ["name", "amount", "periodStart", "periodEnd"],
  ),
  UpdateBudgetRequest: props({
    name: { type: "string" },
    projectId: objectId,
    categoryId: objectId,
    amount: money(),
    periodStart: dateTime(),
    periodEnd: dateTime(),
    status: ref("BudgetStatus"),
  }),

  Dashboard: {
    type: "object",
    description: "Role-scoped executive dashboard. Finance fields are omitted for EMPLOYEE.",
    additionalProperties: true,
    properties: {
      date: { type: "string", format: "date" },
      timezone: { type: "string", example: "Asia/Kolkata" },
      tasks: { type: "object", additionalProperties: true },
      meetings: { type: "object", additionalProperties: true },
      projects: { type: "object", additionalProperties: true },
      sales: { type: "object", additionalProperties: true },
      finance: { type: "object", additionalProperties: true, description: "Company finance. Hidden from EMPLOYEE." },
      attention: { type: "array", items: { type: "object", additionalProperties: true } },
    },
  },

  AssistantQueryRequest: props(
    {
      message: { type: "string", maxLength: 2000, example: "What tasks are pending?" },
      conversationId: { type: "string", maxLength: 100, example: "CONV-001" },
    },
    ["message"],
  ),
  AssistantQueryResponse: props({
    queryId: { type: "string", example: "QRY-000001" },
    intent: ref("AssistantIntent"),
    answer: { type: "string", example: "You have 12 pending tasks." },
    data: { type: "object", additionalProperties: true, description: "Structured payload for Flutter. Do not parse answer." },
    sources: { type: "array", items: { type: "string" } },
    confidence: { type: "number", minimum: 0, maximum: 1, example: 0.98 },
  }),
  AssistantQueryHistoryItem: props({
    queryId: { type: "string" },
    conversationId: { type: "string" },
    message: { type: "string" },
    intent: ref("AssistantIntent"),
    answer: { type: "string" },
    status: ref("AssistantQueryStatus"),
    createdAt: dateTime(),
  }),

  AssistantActionRequest: props(
    {
      message: { type: "string", maxLength: 2000, example: "Create a task to call ABC tomorrow" },
      conversationId: { type: "string", maxLength: 100 },
    },
    ["message"],
  ),
  ConfirmActionRequest: props({ confirmed: { type: "boolean", example: true } }, ["confirmed"]),
  AssistantActionResponse: props({
    actionId: { type: "string", example: "ACT-000001" },
    intent: ref("AssistantActionIntent"),
    status: ref("AssistantActionStatus"),
    message: { type: "string" },
    result: { type: "object", additionalProperties: true },
    requiresConfirmation: { type: "boolean" },
  }),
  AssistantActionHistoryItem: props({
    actionId: { type: "string" },
    intent: ref("AssistantActionIntent"),
    status: ref("AssistantActionStatus"),
    message: { type: "string" },
    createdAt: dateTime(),
    completedAt: { ...dateTime(), nullable: true },
    processingTimeMs: { type: "integer" },
  }),

  ReminderRecurrence: props({
    enabled: { type: "boolean" },
    frequency: ref("ReminderFrequency"),
    interval: { type: "integer", minimum: 1, maximum: 30 },
    daysOfWeek: { type: "array", items: ref("ReminderWeekday") },
    endAt: { ...dateTime(), nullable: true },
  }),
  Reminder: props({
    id: objectId,
    reminderId: { type: "string", example: "REM-000001" },
    userId: objectId,
    createdBy: objectId,
    title: { type: "string", example: "Call ABC Industries" },
    description: { type: "string" },
    reminderType: ref("ReminderType"),
    sourceType: ref("ReminderSourceType"),
    sourceId: { ...objectId, nullable: true },
    scheduledAt: dateTime(),
    timezone: { type: "string", example: "Asia/Kolkata" },
    priority: ref("ReminderPriority"),
    status: ref("ReminderStatus"),
    recurrence: ref("ReminderRecurrence"),
    actionUrl: { type: "string" },
    nextRunAt: { ...dateTime(), nullable: true },
    triggeredAt: { ...dateTime(), nullable: true },
    completedAt: { ...dateTime(), nullable: true },
    cancelledAt: { ...dateTime(), nullable: true },
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  CreateReminderRequest: props(
    {
      title: { type: "string", example: "Call ABC Industries" },
      description: { type: "string" },
      reminderType: ref("ReminderType"),
      sourceType: ref("ReminderSourceType"),
      sourceId: objectId,
      scheduledAt: dateTime(),
      timezone: { type: "string", example: "Asia/Kolkata" },
      priority: ref("ReminderPriority"),
      actionUrl: { type: "string" },
      recurrence: ref("ReminderRecurrence"),
    },
    ["title", "scheduledAt"],
  ),
  UpdateReminderRequest: props({
    title: { type: "string" },
    description: { type: "string" },
    scheduledAt: dateTime(),
    timezone: { type: "string" },
    priority: ref("ReminderPriority"),
    actionUrl: { type: "string" },
  }),
  SnoozeReminderRequest: props({ scheduledAt: dateTime() }, ["scheduledAt"]),

  Notification: props({
    id: objectId,
    notificationId: { type: "string", example: "NOTIF-000001" },
    recipientId: objectId,
    type: ref("NotificationType"),
    category: ref("NotificationCategory"),
    title: { type: "string" },
    message: { type: "string" },
    priority: ref("NotificationPriority"),
    isRead: { type: "boolean" },
    readAt: { ...dateTime(), nullable: true },
    status: ref("NotificationDeliveryStatus"),
    sourceType: { type: "string" },
    sourceId: { ...objectId, nullable: true },
    actionUrl: { type: "string" },
    sentAt: { ...dateTime(), nullable: true },
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  UnreadCount: props({ count: { type: "integer", example: 3 } }),

  NotificationPreference: props({
    userId: objectId,
    channels: props({
      inApp: { type: "boolean", example: true },
      email: { type: "boolean", example: false },
      sms: { type: "boolean", example: false },
      push: { type: "boolean", example: false },
      whatsapp: { type: "boolean", example: false },
    }),
    categories: props({
      tasks: { type: "boolean" },
      meetings: { type: "boolean" },
      projects: { type: "boolean" },
      crm: { type: "boolean" },
      finance: { type: "boolean" },
      reminders: { type: "boolean" },
      system: { type: "boolean" },
    }),
    quietHours: props({
      enabled: { type: "boolean" },
      startTime: { type: "string", example: "22:00" },
      endTime: { type: "string", example: "07:00" },
      timezone: { type: "string", example: "Asia/Kolkata" },
    }),
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  UpdateNotificationPreferenceRequest: props({
    channels: props({
      inApp: { type: "boolean" },
      email: { type: "boolean" },
      sms: { type: "boolean" },
      push: { type: "boolean" },
      whatsapp: { type: "boolean" },
    }),
    categories: props({
      tasks: { type: "boolean" },
      meetings: { type: "boolean" },
      projects: { type: "boolean" },
      crm: { type: "boolean" },
      finance: { type: "boolean" },
      reminders: { type: "boolean" },
      system: { type: "boolean" },
    }),
    quietHours: props({
      enabled: { type: "boolean" },
      startTime: { type: "string", example: "22:00" },
      endTime: { type: "string", example: "07:00" },
      timezone: { type: "string" },
    }),
  }),

  WhatsAppLinkCodeResponse: props({
    code: { type: "string", example: "482913", description: "Plaintext shown once. Stored as a hash." },
    expiresAt: dateTime(),
  }),
  WhatsAppLinkCancelResponse: props({ cancelled: { type: "boolean", example: true } }),
  WhatsAppWebhookAck: props({ success: { type: "boolean", example: true } }),
  WhatsAppWebhookPayload: {
    type: "object",
    additionalProperties: true,
    description: "Meta Cloud API webhook envelope. The API classifies messages vs status events and does not treat every payload as a user message.",
    example: {
      object: "whatsapp_business_account",
      entry: [
        {
          changes: [
            {
              value: {
                messages: [
                  {
                    from: "919876500801",
                    id: "wamid.example",
                    timestamp: "1724160000",
                    type: "text",
                    text: { body: "What tasks are pending?" },
                  },
                ],
              },
            },
          ],
        },
      ],
    },
  },

  Health: props({ timestamp: dateTime() }),
  DatabaseHealth: props({ connected: { type: "boolean", example: true }, timestamp: dateTime() }),
};

function errorResponse(description: string, exampleMessage: string, statusNote?: string) {
  return {
    description: statusNote ? `${description}. ${statusNote}` : description,
    content: {
      "application/json": {
        schema: ref("ApiError"),
        example: { success: false, message: exampleMessage, errors: [] },
      },
    },
  };
}

export const componentResponses = {
  BadRequest: errorResponse("Bad request", "Invalid identifier"),
  Unauthorized: errorResponse("Authentication required", "Authentication required"),
  Forbidden: errorResponse("Forbidden", "You do not have permission to perform this action"),
  NotFound: errorResponse("Not found", "Resource not found"),
  Conflict: errorResponse("Conflict", "Resource already exists"),
  ValidationError: errorResponse("Request validation failed", "Validation failed"),
  TooManyRequests: errorResponse("Rate limit exceeded", "Too many requests. Please try again later."),
  InternalServerError: errorResponse("Internal server error", "Internal server error"),
  ServiceUnavailable: errorResponse("Service unavailable", "Database is not connected"),
};

export const componentSecuritySchemes = {
  BearerAuth: {
    type: "http",
    scheme: "bearer",
    bearerFormat: "JWT",
    description: "Application JWT from POST /api/v1/auth/login. Send as `Authorization: Bearer <token>`.",
  },
};
